version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    build: .
    ports:
      - "4000:4000"